### PR TITLE
Added srcset resolving for each of the srcsets of <img>

### PR DESCRIPTION
**Pull request by knidarkness**
This PR addresses #32 about resolving `srcset` fields. 

The logic is the same as for the `img src="..."` .

We might decide to store only one secret value, to reduce the size of the bundle.

### CODE REVIEW

**Comment by snshn** [comment]
Hey, thank you for working on this!

I've tested it against https://www.vanseodesign.com/blog/demo/responsive-images/ and it seems like the srcset attribute gets replaced with dataURL of the first asset in the chain, rather than replacing each source with a corresponding dataURL, preserving the size parameter in a comma-separated way.
This is definitely an improvement, as currently monolith-saved pages show broken images whenever srcset is used, I just think this PR needs to be polished up a bit before we merge this into master. Thanks a lot for helping out on this once again!

**Comment by knidarkness** [comment]
Thanks for checking, my fault on that. Will fix that today/tomorrow. Btw, could you give a look at #73 ? It's in draft stage, but would appreciate your feedback for approach itself.

**Comment by snshn** [comment]
It's all good, I think the srcset is almost done, just needs a bit of testing and then I'll merge it in. Will take a look at #73 now, thanks for the heads up!

**Comment by snshn** [comment]
I'm also thinking this code could be used to properly embed assets for `<picture><source srcset="..."/></picture>`. Perhaps if we make a function out of the current implementation it could cover both cases easily, plus it should be easier to test it.

**Pull request closed without merging**
