### PR TITLE
add Dockerfile

### LINKED ISSUE #128: installation: add a dockerfile
add an option to run monolith in docker. something like [this](https://raw.githubusercontent.com/grerrg/container-monolith/master/Dockerfile):
```
FROM rust

ADD https://codeload.github.com/Y2Z/monolith/tar.gz/v2.1.2 /usr/local/src/monolith.tar.gz
WORKDIR /usr/local/src/
RUN tar xvfz monolith.tar.gz \
 && rm monolith.tar.gz \
 && mv * monolith
WORKDIR /usr/local/src/monolith
RUN make install

CMD ["/usr/local/cargo/bin/monolith"]
```

### PR DESCRIPTION
**Pull request by snshn**
Resolves #128

### CODE REVIEW

**Comment by snshn** [comment]
I run mine like this: `docker run monolith monolith https://github.com | cat > github.html`. Do you know a better way to run containerized cli tools, or that's as convenient as it gets? In other words, if there's anything you'd like me to improve in regards to Dockerfile, please lmk, otherwise I'll merge this PR into master for everybody to use.

**Comment by grerrg** [comment]
I'm glad you asked. I usually place a script int `~/.local/bin` which may look like this:
```
#!/bin/sh
docker run --rm -ti \
    -v $(pwd):/data \
    --user $(id --user) \
    grerrg/git \
    git
    "$@"
```
This is for me a seamless integration of software running in container and having it interacting with the host. The current path will be mounted into the containers workdir. An the output file has the same owner as the user running it.

I wanted to post a more complex run script which should bring functionality like mentioned in #50 on the table.
Like this:
  * loop the executable over input list
  * create directories for `domain+tld`
But i have no idea how to sanitize an URL in a matter that fits into file system reading. I want to say that i don't know to to thread special characters.

**Comment by snshn** [comment]
Thank you for the info. Please don't worry about those additions, they should be part of this tool anyway. I should be able to implement them once more important issues are resolved.

**Comment by grerrg** [comment]
I'd go with this one for monolith:
```sh
#!/bin/sh
docker run --rm -ti \
    -v $(pwd):/data \
    --user $(id --user) \
    Y2Z/monolith \
    monolith
    "$@"
```
and advise to put this as a script in `~/.local/bin/container-monolith` and make it executable.

There are other options like putting in a `label` for the `atomic` environment. But `atomic` isn't that much distributed at all imho.
Or just running it in a multi-line command. But this one i dislike much. For example `$(pwd)` isn't recognized by the `fish shell`. The above method allows other users to make their own changes in however they want to run `monolith` in a container.

**Comment by snshn** [comment]
Created a wiki page https://github.com/Y2Z/monolith/wiki/Using-containers and linked it from the README (it's getting too big at this point, couldn't include all the necessary information about containers without bloating it). Thank you for your help on this and please let me know here or in a separate issue if there's anything I could improve in regards of Dockerfile or any other part of the program!

**Comment by grerrg** [comment]
creating documentation is always great. but whether the wiki is the right place i'm not sure. How can i contribute to the wiki?
I think having a long mono readme isn't that bad, since you wiki pages aren't cloned with `git clone`. I mirrored your repo to mine `gitea` and the wiki pages aren't mirrored with.

Regarding the wiki entry:
If you want to pipe monolith's (running in a container) output to a local file that's fine. But you won't need these flags:
```shell
docker run --rm \
#    -v $(pwd):/data \
#    --user $(id --user) \
    y2z/monolith \
    monolith \
    "$@"
```

**Comment by snshn** [comment]
You're right, only contributors or members of the organization seem to be able to edit wiki pages on GitHub. You're also making a good point regarding this information not traveling along with the rest of the code base when it's forked/cloned/mirrored. I'll move pages from wiki under `docs/` and likely close the wiki section completely.

**Comment by snshn** [comment]
Hey there @grerrg 

I've opened #133 to move the instructions out of wiki into docs, could you please review it whenever you get a chance?

**Pull request merged**
