### PR TITLE
Remove lazy-static crate dependency

### PR DESCRIPTION
**Pull request by snshn**

### CODE REVIEW

**Comment by Alch-Emi** [comment]
May I ask the reasoning behind this?  Wouldn't this mean that we have to recompile the regexs with each of these function calls?

**Comment by snshn** [comment]
Yeah, having to recompile regexes every time is the downside here. The main idea was to reduce the amount of dependencies, nothing else really -- it feels like a slight overhead, but the win is one crate less to depend on. I was actually curious how beneficial to the project you think it is to slightly sacrifice performance for having less direct dependencies. It's not a big change so closing this PR without merging is absolutely not a problem.

**Comment by Alch-Emi** [comment]
I know this is closed at this point anyway, but in case anyone comes back to it for archival purposes, it might be worth noting that `lazy_static` is a dependency of `regex`, so removing it from our depends won't reduce build size.

**Comment by snshn** [comment]
Thanks for the info Emi. Originally I thought of getting rid of both of those crates, while none of them were heavily used, but now regex has far bigger significance to the program, hence there's no longer a point in doing that.

**Pull request closed without merging**
